import type { components } from './generated/openapi';

export type Schemas = components['schemas'];
export type ApiErrorBody = Schemas['ErrorResponseDto'];
export type HealthResponse = Schemas['HealthResponseDto'];
export type LoginRequest = Schemas['LoginDto'];
export type LoginResponse = Schemas['LoginResponseDto'];
export type CurrentUser = Schemas['MeResponseDto'];
export type Role = CurrentUser['role'];
export type CurrentOrganization = Schemas['MeOrganizationDto'];
export type Vehicle = Schemas['VehicleResponseDto'];
export type VehicleList = Schemas['VehicleListResponseDto'];
export type CreateVehicleRequest = Schemas['CreateVehicleDto'];
export type UpdateVehicleRequest = Schemas['UpdateVehicleDto'];
export type User = Schemas['UserResponseDto'];
export type UserList = Schemas['UserListResponseDto'];
export type CreateUserRequest = Schemas['CreateUserDto'];
export type UpdateUserRequest = Schemas['UpdateUserDto'];
export type ChangePasswordRequest = Schemas['ChangePasswordDto'];
export type Driver = Schemas['DriverResponseDto'];
export type DriverList = Schemas['DriverListResponseDto'];
export type CreateDriverRequest = Schemas['CreateDriverDto'];
export type UpdateDriverRequest = Schemas['UpdateDriverDto'];
export type Assignment = Schemas['AssignmentResponseDto'];
export type AssignmentList = Schemas['AssignmentListResponseDto'];
export type CreateAssignmentRequest = Schemas['CreateAssignmentDto'];
